export const PERMISSIONS = {
  PRODUCTS_CREATE: 'products:create',
  PRODUCTS_READ: 'products:read',
  PRODUCTS_UPDATE: 'products:update',
  PRODUCTS_DELETE: 'products:delete',
  CATEGORIES_CREATE: 'categories:create',
  CATEGORIES_READ: 'categories:read',
  CATEGORIES_UPDATE: 'categories:update',
  CATEGORIES_DELETE: 'categories:delete',
  ORDERS_READ: 'orders:read',
  ORDERS_UPDATE: 'orders:update',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  ROLES_CREATE: 'roles:create',
  ROLES_READ: 'roles:read',
  ROLES_UPDATE: 'roles:update',
  ROLES_DELETE: 'roles:delete',
  PERMISSIONS_CREATE: 'permissions:create',
  PERMISSIONS_READ: 'permissions:read',
  PERMISSIONS_UPDATE: 'permissions:update',
  PERMISSIONS_DELETE: 'permissions:delete',
  REVIEWS_READ: 'reviews:read',
  REVIEWS_DELETE: 'reviews:delete',
  COUPONS_CREATE: 'coupons:create',
  COUPONS_READ: 'coupons:read',
  COUPONS_UPDATE: 'coupons:update',
  COUPONS_DELETE: 'coupons:delete',
  WISHLIST_READ: 'wishlist:read',
  UPLOADS_CREATE: 'uploads:create',
  DASHBOARD_READ: 'dashboard:read',
  SHOPS_CREATE: 'shops:create',
  SHOPS_READ: 'shops:read',
  SHOPS_UPDATE: 'shops:update',
} as const;

export type PermissionString = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
